apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-z1ci
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-z1ci
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-z1ci
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-z1ci
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-z1ci
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-suyg-tenant/rhtap-demo-app/hacbs-test-project-z1ci@sha256:c836b31239316553c398f5973d7e725b826fb865d9fe2a088252a258e5e4cfbc
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
